# 
# Do NOT Edit the Auto-generated Part!
# Generated by: spectacle version 0.26
# 

Name:       nemo-configs-minnowboard

# >> macros
# << macros

Summary:    Some configs for x86_64 Minnowboard adaptation in Nemo Mobile
Version:    0.1
Release:    1
Group:      Configs
License:    GPLv2
BuildArch:  noarch
URL:        https://github.com/nemomobile/nemo-configs-x86
Source0:    %{name}-%{version}.tar.bz2

%description
%{summary}.


%package common
Summary:    Common files shared by both Xorg and Wayland for x86 vm adaptation
Group:      Configs

%description common
%{summary}.


%package wayland
Summary:    Wayland Configs for x86 vm adaptation
Group:      Configs
Requires:   nemo-configs-minnowboard-common
Conflicts:  nemo-configs-x86-vm-xorg

%description wayland
%{summary}.


%package generic
Summary:    Configs for generic x86 adaptation
Group:      Configs
Provides:   nemo-mobile-configs-x86-generic > 2
Obsoletes:  nemo-mobile-configs-x86-generic <= 2

%description generic
%{summary}.


%prep
%setup -q -n %{name}-%{version}

# >> setup
# << setup

%build
# >> build pre
# << build pre



# >> build post
# << build post

%install
rm -rf %{buildroot}
# >> install pre
%make_install
# << install pre

# >> install post
# << install post


%files common
%defattr(-,root,root,-)
%{_sharedstatedir}/environment/nemo/61-x86-vm.conf
# >> files vm-common
# << files vm-common

%files wayland
%defattr(-,root,root,-)
%{_sharedstatedir}/environment/compositor/61-x86-vm-ui.conf
# >> files vm-wayland
# << files vm-wayland

%files generic
%defattr(-,root,root,-)
%{_sharedstatedir}/environment/nemo/61-x86-generic.conf
# >> files generic
# << files generic
